name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/setup@v2
        with:
          runtime: node@26
          cache: true

      - name: Run lint tests
        run: pnpm run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/setup@v2
        with:
          runtime: node@26
          cache: true

      - name: Conduct typecheck
        run: pnpm run typecheck

  test:
    name: Vitest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/setup@v2
        with:
          runtime: node@26
          cache: true

      - name: Conduct tests
        run: pnpm run test

  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/setup@v2
        with:
          runtime: node@26
          cache: true

      - name: Perform build
        run: pnpm run build

      - uses: actions/upload-artifact@v7
        with:
          name: build-artifact
          path: build/
          retention-days: 3